// Code generated by protoc-gen-go.
// source: poe.proto
// DO NOT EDIT!

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	poe.proto

It has these top-level messages:
	Document
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ProofObject
type Document struct {
	// unique id
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// raw data
	Raw []byte `protobuf:"bytes,2,opt,name=raw,proto3" json:"raw,omitempty"`
	// hash(block)
	BlockDigest string `protobuf:"bytes,3,opt,name=blockDigest" json:"blockDigest,omitempty"`
	// submit time
	SubmitTime int64 `protobuf:"varint,4,opt,name=submitTime" json:"submitTime,omitempty"`
	// proof time
	ProofTime int64 `protobuf:"varint,5,opt,name=proofTime" json:"proofTime,omitempty"`
}

func (m *Document) Reset()                    { *m = Document{} }
func (m *Document) String() string            { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()               {}
func (*Document) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterType((*Document)(nil), "protos.Document")
}

func init() { proto.RegisterFile("poe.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 128 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2c, 0xc8, 0x4f, 0xd5,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0x53, 0xc5, 0x4a, 0xf1, 0x5c, 0x1c, 0x2e, 0xf9,
	0xc9, 0xa5, 0xb9, 0xa9, 0x79, 0x25, 0x42, 0x5c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0x9c, 0x42, 0xdc, 0x5c, 0xcc, 0x45, 0x89, 0xe5, 0x12, 0x4c, 0x40, 0x0e, 0x8f, 0x90, 0x30,
	0x17, 0x77, 0x52, 0x4e, 0x7e, 0x72, 0xb6, 0x4b, 0x66, 0x7a, 0x6a, 0x71, 0x89, 0x04, 0x33, 0x58,
	0x05, 0x50, 0x79, 0x71, 0x69, 0x52, 0x6e, 0x66, 0x49, 0x48, 0x66, 0x6e, 0xaa, 0x04, 0x0b, 0x50,
	0x8c, 0x59, 0x48, 0x10, 0x68, 0x45, 0x51, 0x7e, 0x7e, 0x1a, 0x58, 0x88, 0x15, 0x24, 0x94, 0x04,
	0xb1, 0xc8, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x14, 0x1e, 0xa3, 0x79, 0x7c, 0x00, 0x00, 0x00,
}
